### ISSUE TITLE
Some things for the design

### ISSUE THREAD

**Issue by tkapias** [TiagoSilvaPereira/laraestimate#19]
I added some scss elements for the view and the print : 

- display for blockquote and blockcode (pre) in the editor style.
- blockquote more centered
- force the styles for print
- force background printing for blockcode at print
- hide the lines that are not selected in the pricing tables for print

``` css
/* Modifications for view and print */
pre {
    display: inline-block;
    width: 100%;
    vertical-align: top;
    font-family: monospace;
    font-size: 0.9em;
    margin: 0;
    padding: 0.5em;
    background-color: #eee;
    -webkit-print-color-adjust: exact;
    color-adjust: exact;
}

blockquote {
    margin: 0 0 0 0.3em;
    padding: 0 1em 0 1em;
    border-left: 0.3em solid #ccc;
}

@media print {
  blockquote {
      margin: 0 0 0 0.3em;
      padding: 0 1em 0 1em;
      border-style: none;
      border-left: 0.3em solid #ccc;
  }
  tr.item:not(.selected) {
      display: none;
  }
}
```
